[changelog]
header = """
# Release Notes\n
"""

body = """
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{%- macro version_title() -%}
  {%- if version -%}
    Release {{ version | trim_start_matches(pat="v") }}
  {%- else -%}
    {%- set version = get_env(name="VERSION", default="") -%}
    {%- if version -%}
      Release {{ version | trim_start_matches(pat="v") }}
    {%- else -%}
      Unreleased
    {%- endif -%}
  {%- endif -%}
{%- endmacro -%}

{%- macro user_link(username) -%}
  {%- set username = username | trim_end_matches(pat="[bot]") -%}
  {%- if get_env(name="CLIFF_SHORT_USERNAME", default="false") == "true" -%}
    @{{ username }}
  {%- else -%}
    [@{{ username }}](https://github.com/{{ username }})
  {%- endif -%}
{%- endmacro -%}

{%- macro pr_link(pr) -%}
  [#{{ pr }}]({{ self::remote_url() }}/pull/{{ pr }})
{%- endmacro -%}

{%- macro format_commit(commit) -%}
  {%- if commit.breaking -%} **BREAKING**: {% endif -%}
  {{ commit.message | upper_first }}
  {%- if commit.remote.username %} \\
    by {{ self::user_link(username=commit.remote.username) }}
  {%- endif -%}
  {%- if commit.remote.pr_number %} \\
    in {{ self::pr_link(pr=commit.remote.pr_number) }}
  {%- endif -%}
{%- endmacro -%}

{%- macro current_ref() -%}
  {%- if version -%}
    {{ version }}
  {%- else -%}
    {{ get_env(name="TAG", default="master") }}
  {%- endif -%}
{%- endmacro -%}

{%- macro full_changelog(prev, current) -%}
  **Full Changelog**: <{{ self::remote_url() }}/compare/{{ prev }}...{{ current }}>
{%- endmacro -%}

## {{ self::version_title()  }}

{% for group, commits in commits | group_by(attribute="group") -%}
    {%- if commits | length > 0 -%}
        ### {{ group | striptags | trim | upper_first }}\n
        {% for commit in commits -%}
          - {{ self::format_commit(commit = commit) }}
        {% endfor -%}
        {{ "\n" }}
    {%- endif -%}
{%- endfor -%}

{%- if previous.version -%}
  {{ self::full_changelog(prev=previous.version, current=self::current_ref()) }}\n
{% endif -%}
"""

trim = true

footer = """
<!-- generated by git-cliff -->
"""

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false

commit_preprocessors = [
  { pattern = ' \\(#([0-9]+)\\)', replace = "" },
]

commit_parsers = [
  { message = "\\[(no|skip) changelog\\]", skip = true },

  { message = "^feat", group = "<!-- 0 -->Features" },
  { message = "^fix", group = "<!-- 1 -->Bug Fixes" },
  { message = "^perf", group = "<!-- 2 -->Performance" },
  { message = "^refactor", group = "<!-- 3 -->Refactor" },
  { message = "^doc", group = "<!-- 4 -->Documentation" },
  { message = "^test", group = "<!-- 5 -->Testing" },

  { body = ".*security", group = "<!-- 6 --> Security" },
  { message = "^[Rr]evert", group = "<!-- 7 --> Revert" },

  { message = "^style", skip = true },
  { message = "^chore\\(style\\)", skip = true },
  { message = "^chore\\(format\\)", skip = true },
  { message = "^chore:.*format", skip = true },

  { message = "^chore\\(release\\): prepare for", skip = true },
  { message = "^chore\\(deps\\)", skip = true },
  { message = "^[Bb]ump", skip = true },
  { message = "^chore: bump", skip = true },

  { message = "^ci", skip = true },

  { message = "^chore\\(changelog\\)", skip = true },
  { message = "^chore: update changelog", skip = true },

  { message = "^chore", group = "<!-- 99 -->Miscellaneous" },
]

protect_breaking_commits = false
filter_commits = false
tag_pattern = "^v[0-9]+\\.[0-9]+\\.[0-9]+$"
topo_order = false
sort_commits = "oldest"

[remote.github]
owner = "lingdiansr"
repo = "wlsnap"
